#!/usr/bin/env python3
"""Module for adding graded exterior tetrahedral layers using MeshPy/TetGen."""

from __future__ import annotations

import argparse
import math
from collections.abc import Sequence
from pathlib import Path

import meshio
import numpy as np
from meshpy.tet import MeshInfo, Options, build  # MeshPy -> TetGen

"""
Add graded tetrahedral layers *outside* an existing body mesh using MeshPy (TetGen),
with flexible control of outermost geometric scale and automatic derivation of
either the per-layer geometric factor K or the number of layers L.

This module provides a pure in-memory API:
    run_add_shell_pipeline(...):  returns (knt, ijk) for the merged (body+shell) mesh
                                  and does **not** write any files.

Key features
------------
- Preserves the original body's surface triangles as the *inner* interface by
  supplying them as PLC facets and using TetGen region attributes and
  volume constraints.
- Builds homothetic shells S_layer_idx = K**layer_idx * S_0, layer_idx=0..L, and
  per-layer region seeds with per-region max volume constraints
  (derived from target h_layer_idx).
- Ties mesh size scaling to geometry with exponent beta:
  h_layer_idx = h0 * (K**beta)**(layer_idx+1),
  unless you give --hmax explicitly (then growth is inferred from hmax/h0).
- Merges body & shell, welds duplicate nodes (0-based, consecutive IDs),
  reorients tets to positive volume, and removes degenerate/duplicate elements.

Inputs (NPZ)
------------
knt : (N,3) float64
ijk : (E,4) or (E,5) int (optional mat_id in column 4)

Outputs (in-memory)
-------------------
knt : fused nodes (float64)
ijk : valid tets with mat_id (int32)

Requirements
------------
- meshpy (TetGen interface) -> pip install meshpy
- TetGen manual on PLC, quality, attributes, volume constraints:
  https://www.wias-berlin.de/software/tetgen/1.5/doc/manual
"""


# ------------------------------- utilities -------------------------------


def log(msg: str) -> None:
    """Print a message to the console with immediate flush.

    Args:
        msg (str): message to log.
    """
    print(msg, flush=True)


def parse_csv3(s: str) -> tuple[float, float, float]:
    """Parse a comma-separated string of 3 floats.

    Args:
        s (str): string like "x,y,z".

    Returns:
        tuple[float, float, float]: (x, y, z).

    Raises:
        ValueError: if string does not contain exactly 3 components.
    """
    a = [float(x) for x in s.split(",")]
    if len(a) != 3:
        raise ValueError("Expected 'x,y,z'.")
    return float(a[0]), float(a[1]), float(a[2])


def approx_max_volume_from_edge(h: float) -> float:
    """Heuristic for TetGen max volume constraint from target edge length.

    Args:
        h (float): target edge length.

    Returns:
        float: max volume constraint (approximately 0.1 * h^3).
    """
    # Heuristic upper bound usable for TetGen -a (max volume per region).
    # We use 0.2 * (h**3) rather than the exact volume of a regular tetrahedron
    # because the mean volume generated by TetGen is typically smaller than the max.
    # A max constraint of 0.2 shifts the mean edge length to accurately reflect target h.
    return 0.2 * (h**3)


def find_outer_surface_tris(ijk: np.ndarray) -> np.ndarray:
    """Extract surface triangles that appear only once in the tetrahedron mesh.

    Args:
        ijk (np.ndarray): Tetrahedron connectivity (E, 4).

    Returns:
        np.ndarray: Surface triangles (T, 3).
    """
    t4 = ijk[:, :4].astype(np.int64)
    fp = np.array([[0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3]], dtype=np.int64)
    faces = t4[:, fp].reshape(-1, 3)
    keys = np.sort(faces, axis=1)
    uniq, inv, cnt = np.unique(keys, axis=0, return_inverse=True, return_counts=True)
    return faces[cnt[inv] == 1]


def find_outer_boundary_mask(ijk: np.ndarray, num_nodes: int) -> np.ndarray:
    """Generate a mask for nodes on the outer surface of the mesh.

    Args:
        ijk (np.ndarray): Tetrahedron connectivity (E, 4).
        num_nodes (int): total number of nodes in the mesh.

    Returns:
        np.ndarray: Mask (N,) where 0.0 is boundary and 1.0 is interior.
    """
    tris = find_outer_surface_tris(ijk)
    boundary_vids = np.unique(tris)
    mask = np.ones(num_nodes, dtype=np.float64)
    mask[boundary_vids] = 0.0
    return mask


def weld_points(knt: np.ndarray, ijk: np.ndarray, tol: float = 1e-12) -> tuple[np.ndarray, np.ndarray, int]:
    """Fuse nodes closer than 'tol' using integer grid hashing.

    Args:
        knt (np.ndarray): original node coordinates (N, 3).
        ijk (np.ndarray): original element connectivity.
        tol (float, optional): welding tolerance. Defaults to 1e-12.

    Returns:
        tuple[np.ndarray, np.ndarray, int]: (Fused nodes, remapped connectivity,
                                            number of merged nodes).
    """
    if knt.size == 0:
        return knt, ijk, 0

    key = np.round(knt / tol).astype(np.int64)
    uniq_key, first_idx = np.unique(key, axis=0, return_index=True)
    id_of_key = {tuple(uniq_key[i]): i for i in range(uniq_key.shape[0])}
    map_old_to_new = np.array([id_of_key[tuple(k)] for k in key], dtype=np.int64)

    knt_weld = knt[first_idx]
    ijk4 = map_old_to_new[ijk[:, :4].astype(np.int64)]

    if ijk.shape[1] >= 5:
        ijk_out = np.hstack([ijk4.astype(np.int32), ijk[:, 4:5].astype(np.int32)])
    else:
        ijk_out = ijk4.astype(np.int32)

    n_merged = knt.shape[0] - knt_weld.shape[0]
    return knt_weld, ijk_out, n_merged


def orient_tets_positive(knt: np.ndarray, tets: np.ndarray) -> np.ndarray:
    """Ensure all tetrahedra have positive volume by swapping nodes if needed.

    Args:
        knt (np.ndarray): node coordinates.
        tets (np.ndarray): connectivity (E, 4).

    Returns:
        np.ndarray: oriented connectivity.
    """
    if tets.size == 0:
        return tets
    t = tets.copy()
    a, b, c, d = knt[t[:, 0]], knt[t[:, 1]], knt[t[:, 2]], knt[t[:, 3]]
    vols6 = np.einsum("ij,ij->i", np.cross(b - a, c - a), d - a)
    bad = vols6 < 0.0
    if np.any(bad):
        tmp = t[bad].copy()
        tmp[:, [1, 2]] = tmp[:, [2, 1]]
        t[bad] = tmp
    return t


def remove_degenerate_and_duplicate_tets(knt: np.ndarray, ijk: np.ndarray, vol_eps: float = 1e-20) -> np.ndarray:
    """Drop tets with repeated nodes, near-zero volume, or identical node sets.

    Args:
        knt (np.ndarray): node coordinates.
        ijk (np.ndarray): element connectivity.
        vol_eps (float, optional): volume threshold. Defaults to 1e-20.

    Returns:
        np.ndarray: cleaned element connectivity.
    """
    t4 = ijk[:, :4].astype(np.int64)
    unique_nodes = np.array([len(set(row)) == 4 for row in t4], dtype=bool)

    a, b, c, d = knt[t4[:, 0]], knt[t4[:, 1]], knt[t4[:, 2]], knt[t4[:, 3]]
    vols6 = np.abs(np.einsum("ij,ij->i", np.cross(b - a, c - a), d - a))
    keep = unique_nodes & (vols6 > vol_eps)
    ijk_kept = ijk[keep]
    if ijk_kept.shape[0] == 0:
        return ijk_kept

    t4s = np.sort(ijk_kept[:, :4], axis=1)
    uniq, first_idx = np.unique(t4s, axis=0, return_index=True)
    return ijk_kept[np.sort(first_idx)]


def compute_tet_quality(knt: np.ndarray, tets: np.ndarray) -> np.ndarray:
    """Computes the normalized volume-to-edge ratio quality metric eta for each tetrahedron."""
    if tets.size == 0:
        return np.array([])
    pts = knt[tets]
    a, b, c, d = pts[:, 0], pts[:, 1], pts[:, 2], pts[:, 3]
    ab, ac, ad, bc, bd, cd = b - a, c - a, d - a, c - b, d - b, d - c
    vols6 = np.abs(np.einsum("ij,ij->i", np.cross(ab, ac), ad))
    vols = vols6 / 6.0
    l_ab, l_ac, l_ad = np.einsum("ij,ij->i", ab, ab), np.einsum("ij,ij->i", ac, ac), np.einsum("ij,ij->i", ad, ad)
    l_bc, l_bd, l_cd = np.einsum("ij,ij->i", bc, bc), np.einsum("ij,ij->i", bd, bd), np.einsum("ij,ij->i", cd, cd)
    S = l_ab + l_ac + l_ad + l_bc + l_bd + l_cd
    rms = np.sqrt(np.maximum(S, 1e-12) / 6.0)
    eta = (6.0 * np.sqrt(2.0) * vols) / (rms**3)
    return np.clip(eta, 0.0, 1.0)


# -------------------------- surface size estimate --------------------------


def estimate_body_h_from_surface(knt: np.ndarray, ijk_with_mat: np.ndarray) -> float:
    """Estimate surface mesh size as the median boundary-edge length.

    Args:
        knt (np.ndarray): node coordinates.
        ijk_with_mat (np.ndarray): tetrahedron connectivity.

    Returns:
        float: median edge length.
    """
    tris = find_outer_surface_tris(ijk_with_mat)
    if tris.size == 0:
        diag = np.linalg.norm(knt.max(0) - knt.min(0))
        return max(1e-6, 0.02 * diag)

    edges = np.vstack(
        [
            np.sort(tris[:, [0, 1]], axis=1),
            np.sort(tris[:, [1, 2]], axis=1),
            np.sort(tris[:, [2, 0]], axis=1),
        ]
    )
    edges = np.unique(edges, axis=0)
    p = knt[edges[:, 0]]
    q = knt[edges[:, 1]]
    lens = np.linalg.norm(q - p, axis=1)
    return max(float(np.median(lens)), 1e-12)


def subdivide_flat_mesh(V: np.ndarray, F: np.ndarray, levels: int) -> tuple[np.ndarray, np.ndarray]:
    """Subdivide flat triangles into 4 similar triangles by inserting midpoints on all edges.

    Args:
        V (np.ndarray): Node coordinates (Nv, 3).
        F (np.ndarray): Triangle connectivity (Nf, 3).
        levels (int): Number of subdivision levels.

    Returns:
        tuple[np.ndarray, np.ndarray]: (Subdivided vertices, Subdivided faces).
    """
    for _ in range(max(0, levels)):
        edge_cache = {}
        new_faces = []
        new_verts = V.tolist()

        def mid_idx(i: int, j: int) -> int:
            key = (i, j) if i < j else (j, i)
            if key in edge_cache:  # noqa: B023
                return edge_cache[key]  # noqa: B023
            vi, vj = np.array(new_verts[i]), np.array(new_verts[j])  # noqa: B023
            vm = 0.5 * (vi + vj)
            new_verts.append(vm.tolist())  # noqa: B023
            idx = len(new_verts) - 1  # noqa: B023
            edge_cache[key] = idx  # noqa: B023
            return idx

        for i, j, k in F:
            a = mid_idx(i, j)
            b = mid_idx(j, k)
            c = mid_idx(k, i)
            new_faces.extend(
                [
                    [i, a, c],
                    [a, j, b],
                    [c, b, k],
                    [a, b, c],
                ]
            )
        V = np.array(new_verts, dtype=np.float64)
        F = np.array(new_faces, dtype=np.int32)
    return V, F


# ------------------------------- PLC builders -------------------------------
def build_layer_nodes(
    knt0: np.ndarray, surf_verts: np.ndarray, center: np.ndarray, K: float, layers: int
) -> tuple[np.ndarray, dict[tuple[int, int], int], list[np.ndarray]]:
    """Create node copies for each surface vertex across layers.

    Geometric scales are K**layer_idx.

    Args:
        knt0 (np.ndarray): original body nodes.
        surf_verts (np.ndarray): indices of nodes on the outer surface.
        center (np.ndarray): ray origin for scaling.
        K (float): geometric growth factor (> 1).
        layers (int): number of shell layers.

    Returns:
        tuple: (All nodes, node map (vid, layer) -> id, list of scaling vectors).
    """
    knt = knt0.copy()

    vmin = np.min(knt0, axis=0)
    vmax = np.max(knt0, axis=0)
    ext = vmax - vmin
    Lmax = float(np.max(ext))

    node_map: dict[tuple[int, int], int] = {}

    for vid in surf_verts:
        node_map[(int(vid), 0)] = int(vid)

    c = center.reshape(1, 3)
    v0 = knt0[surf_verts] - c  # rays from center to surface verts

    max_anisotropy = 5.0

    # Print header once (before your loop)
    print(f"{'Layer':>5} | {'sx':>10} | {'sy':>10} | {'sz':>10}")
    print("-" * 5 + "-+-" + "-" * 10 + "-+-" + "-" * 10 + "-+-" + "-" * 10)

    svecs_layer = []
    for layer_idx in range(1, layers + 1):
        s = K**layer_idx
        t = layer_idx / layers if layers > 1 else 1.0
        L_target = s * Lmax
        sx = np.array([L_target / ext[0], L_target / ext[1], L_target / ext[2]], dtype=float)
        sv = (1 - t) * np.array([1.0, 1.0, 1.0]) + t * sx

        ext_layer = ext * sv
        r = ext_layer.max() / max(ext_layer.min(), 1e-12)
        if r > max_anisotropy:
            # softly clamp: scale towards the geometric mean
            g = np.exp(np.log(ext_layer).mean())
            # blend towards isotropy keeping product constant
            alpha = r / max_anisotropy  # >1
            ext_layer = g * (ext_layer / g) ** (1.0 / alpha)
            sv = ext_layer / ext

        # pts = c + s * v0
        print(f"{layer_idx:5d} | {sv[0]:10.6f} | {sv[1]:10.6f} | {sv[2]:10.6f}")
        pts = c + v0 * sv.reshape(1, 3)
        start = knt.shape[0]
        knt = np.vstack([knt, pts])
        for i, vid in enumerate(surf_verts):
            node_map[(int(vid), layer_idx)] = start + i

        svecs_layer.append(sv.copy())

    return knt, node_map, svecs_layer


def make_shell_plc_from_surface(  # noqa: D417
    knt0: np.ndarray,
    tris0: np.ndarray,
    layers: int,
    K: float,
    center: tuple[float, float, float],
    shell_type: str = "box",
    target_h: float | None = None,
) -> tuple[np.ndarray, list[list[int]], np.ndarray, np.ndarray, dict, list]:
    """Build a TetGen PLC with nested homothetic surfaces for shell meshing.

    Args:
        knt0: body nodes.
        tris0: body surface triangles.
        layers: number of layers.
        K: per-layer scale.
        center: ray origin.
        shell_type: 'triangles', 'hull', or 'box'.
        target_h: target mesh size.

    Returns:
        tuple: (All nodes, facets, seeds, surface vertex indices, node map,
                scaling vectors).
    """
    center = np.asarray(center, dtype=np.float64)
    tris0 = np.sort(tris0.astype(np.int64), axis=1)
    surf_verts = np.unique(tris0.reshape(-1))

    if shell_type in ("hull", "box"):
        if shell_type == "hull":
            from scipy.spatial import ConvexHull

            hull = ConvexHull(knt0)
            hull_verts_orig = np.unique(hull.simplices.reshape(-1))
            hull_V = knt0[hull_verts_orig].copy()
            old_to_new = {old: new for new, old in enumerate(hull_verts_orig)}
            hull_F = np.array([[old_to_new[v] for v in tri] for tri in hull.simplices], dtype=np.int32)
        else:  # box
            vmin = np.min(knt0, axis=0)
            vmax = np.max(knt0, axis=0)
            hull_V = np.array(
                [
                    [vmin[0], vmin[1], vmin[2]],
                    [vmax[0], vmin[1], vmin[2]],
                    [vmax[0], vmax[1], vmin[2]],
                    [vmin[0], vmax[1], vmin[2]],
                    [vmin[0], vmin[1], vmax[2]],
                    [vmax[0], vmin[1], vmax[2]],
                    [vmax[0], vmax[1], vmax[2]],
                    [vmin[0], vmax[1], vmax[2]],
                ],
                dtype=np.float64,
            )
            hull_F = np.array(
                [
                    [0, 2, 1],
                    [0, 3, 2],
                    [4, 5, 6],
                    [4, 6, 7],
                    [0, 1, 5],
                    [0, 5, 4],
                    [2, 3, 7],
                    [2, 7, 6],
                    [1, 2, 6],
                    [1, 6, 5],
                    [3, 0, 4],
                    [3, 4, 7],
                ],
                dtype=np.int32,
            )

        # Compute subdivision levels
        levels = 0
        if target_h is not None and target_h > 0:
            edges = np.vstack([hull_F[:, [0, 1]], hull_F[:, [1, 2]], hull_F[:, [2, 0]]])
            lens = np.linalg.norm(hull_V[edges[:, 1]] - hull_V[edges[:, 0]], axis=1)
            avg_len = np.mean(lens)
            desired_len = target_h * 2.0  # Allow some coarseness
            if avg_len > desired_len:
                levels = int(np.ceil(np.log2(avg_len / desired_len)))
                levels = min(levels, 4)  # Cap at 4 levels (256x triangles) to prevent explosion

        hull_V, hull_F = subdivide_flat_mesh(hull_V, hull_F, levels)
        hull_verts = np.arange(len(hull_V))
        hull_tris = hull_F

        # Build node map & scaling copy for layers 1..L using hull_verts
        knt_all = knt0.copy()
        node_map: dict[tuple[int, int], int] = {}
        for vid in surf_verts:
            node_map[(int(vid), 0)] = int(vid)

        vmin = np.min(knt0, axis=0)
        vmax = np.max(knt0, axis=0)
        ext = vmax - vmin
        Lmax = float(np.max(ext))
        c = center.reshape(1, 3)
        v0 = hull_V - c  # rays from center to hull vertices

        max_anisotropy = 5.0
        svecs_layer = []

        print(f"{'Layer':>5} | {'sx':>10} | {'sy':>10} | {'sz':>10}")
        print("-" * 5 + "-+-" + "-" * 10 + "-+-" + "-" * 10 + "-+-" + "-" * 10)

        for layer_idx in range(1, layers + 1):
            s = K**layer_idx
            t = layer_idx / layers if layers > 1 else 1.0
            L_target = s * Lmax
            sx = np.array([L_target / ext[0], L_target / ext[1], L_target / ext[2]], dtype=float)
            sv = (1 - t) * np.array([1.0, 1.0, 1.0]) + t * sx

            ext_layer = ext * sv
            r = ext_layer.max() / max(ext_layer.min(), 1e-12)
            if r > max_anisotropy:
                g = np.exp(np.log(ext_layer).mean())
                alpha = r / max_anisotropy
                ext_layer = g * (ext_layer / g) ** (1.0 / alpha)
                sv = ext_layer / ext

            print(f"{layer_idx:5d} | {sv[0]:10.6f} | {sv[1]:10.6f} | {sv[2]:10.6f}")
            pts = c + v0 * sv.reshape(1, 3)
            start = knt_all.shape[0]
            knt_all = np.vstack([knt_all, pts])
            for i, vid in enumerate(hull_verts):
                node_map[(int(vid), layer_idx)] = start + i

            svecs_layer.append(sv.copy())

        # Build facets
        facets: list[list[int]] = []
        # Layer 0 uses the original surface triangles
        for tri in tris0:
            v = [node_map[(int(tri[0]), 0)], node_map[(int(tri[1]), 0)], node_map[(int(tri[2]), 0)]]
            facets.append(v)
        # Layers 1..L use the scaled convex hull triangles
        for layer_idx in range(1, layers + 1):
            for tri in hull_tris:
                v = [
                    node_map[(int(tri[0]), layer_idx)],
                    node_map[(int(tri[1]), layer_idx)],
                    node_map[(int(tri[2]), layer_idx)],
                ]
                facets.append(v)

        # Build seeds:
        seeds = []
        # Region 0: between layer 0 (tris0) and layer 1 (hull_tris)
        tri0 = tris0[0]
        ctr0 = knt0[tri0].mean(axis=0)
        sv1 = svecs_layer[0]
        ctr1 = c.ravel() + (ctr0 - c.ravel()) * sv1
        seeds.append(0.5 * (ctr0 + ctr1))

        # Subsequent regions: between hull layer l and l+1
        hull_tri0 = hull_tris[0]

        def hull_centroid_at(layer: int) -> np.ndarray:
            vids = [node_map[(int(v), layer)] for v in hull_tri0]
            return knt_all[vids].mean(axis=0)

        for layer_idx in range(1, layers):
            seeds.append(0.5 * (hull_centroid_at(layer_idx) + hull_centroid_at(layer_idx + 1)))

        seeds = np.vstack(seeds).astype(np.float64)

    else:
        # Standard: copy original surface triangles to each scaled layer
        knt_all, node_map, svecs_layer = build_layer_nodes(knt0, surf_verts, center, K, layers)

        facets: list[list[int]] = []
        for layer_idx in range(0, layers + 1):
            for tri in tris0:
                v = [
                    node_map[(int(tri[0]), layer_idx)],
                    node_map[(int(tri[1]), layer_idx)],
                    node_map[(int(tri[2]), layer_idx)],
                ]
                facets.append(v)

        tri0 = tris0[0]

        def centroid_at(layer: int) -> np.ndarray:
            vids = [node_map[(int(v), layer)] for v in tri0]
            return knt_all[vids].mean(axis=0)

        seeds = np.vstack(
            [0.5 * (centroid_at(layer_idx) + centroid_at(layer_idx + 1)) for layer_idx in range(layers)]
        ).astype(np.float64)

    # Optional sanity check:
    assert seeds.shape == (layers, 3)

    return knt_all, facets, seeds, surf_verts, node_map, svecs_layer


# ------------------------------ meshing core ------------------------------
def add_shell_with_meshpy(  # noqa: D417
    knt0: np.ndarray,
    ijk0: np.ndarray,
    layers: int,
    K: float,
    beta: float,
    center: tuple[float, float, float],
    h0: float | None,
    hmax: float | None,
    minratio: float,
    max_steiner: int | None,
    no_exact: bool,
    verbose: bool,
    same_scaling: bool,
    shell_type: str = "box",
) -> tuple[np.ndarray, np.ndarray]:
    """Invoke TetGen to mesh exterior shell layers and merge with the body.

    Args:
        knt0 (np.ndarray): Body nodes.
        ijk0 (np.ndarray): Body connectivity.
        layers (int): Number of shell layers.
        K (float): Geometric factor.
        beta (float): Size scaling exponent.
        center (tuple[float, float, float]): Ray origin.
        h0 (float | None): Target edge length at interface.
        hmax (float | None): Target edge length at boundary.
        minratio (float): TetGen quality constraint.
        max_steiner (int | None): Limit on Steiner points.
        no_exact (bool): Suppress exact arithmetic.
        verbose (bool): Verbose logging.
        same_scaling (bool): Use linear size scaling.

    Returns:
        tuple[np.ndarray, np.ndarray]: (Merged nodes, Merged connectivity).
    """
    # Ensure we have mat_id column
    if ijk0.shape[1] >= 5:
        body_mat = int(ijk0[:, 4].max())
        ijk_body = ijk0[:, :5].astype(np.int32)
    else:
        body_mat = 1
        ijk_body = np.hstack(
            [
                ijk0[:, :4].astype(np.int32),
                np.full((ijk0.shape[0], 1), body_mat, dtype=np.int32),
            ]
        )
    shell_mat = body_mat + 1

    tris0 = find_outer_surface_tris(ijk_body)
    if tris0.size == 0:
        raise RuntimeError("Could not find outer surface triangles.")

    # PLC creation
    knt_plc, facets, seeds, surf_verts, node_map, svecs_layer = make_shell_plc_from_surface(
        knt0, tris0, layers=layers, K=K, center=center, shell_type=shell_type, target_h=h0
    )

    mi = MeshInfo()
    mi.set_points(knt_plc.tolist())
    mi.set_facets(facets)  # PLC facets (triangles)

    # Mesh only the *interior of shells* outside body: mark body interior as a hole
    body_centroid = np.mean(knt0[surf_verts], axis=0)
    mi.set_holes([tuple(body_centroid)])

    # ---- Per-layer size schedule ----
    if same_scaling:
        beta = 1.0

    if h0 is None:
        raise RuntimeError("Internal error: h0 must be resolved before calling add_shell_with_meshpy.")

    # New: drive h_layer_idx from the actual sv used for S_{layer_idx+1}
    gms = [float(np.exp(np.log(sv).mean())) for sv in svecs_layer]  # geometric means (length 'layers')

    if hmax is None:
        # Prevent explosion for large magnets with fine surface meshes (e.g. 200nm magnet with 2nm mesh)
        # by ensuring the outer elements are at least a fraction of the total airbox size.
        ext = np.max(knt0, axis=0) - np.min(knt0, axis=0)
        Lmax = float(np.max(ext))
        base_hmax = h0 * (gms[-1] ** beta)
        # Auto hmax: 20% of the core size scaled by KL
        auto_hmax = 0.2 * Lmax * gms[-1]
        resolved_hmax = max(base_hmax, auto_hmax)
    else:
        resolved_hmax = float(hmax)

    # ensure the *outermost* region hits the resolved hmax
    denom = max(h0 * (gms[-1] ** beta), 1e-30)
    scale = resolved_hmax / denom

    mi.regions.resize(layers)
    for layer_idx in range(layers):
        # region layer_idx is between S_layer_idx and S_{layer_idx+1}
        h_layer_idx = scale * h0 * (gms[layer_idx] ** beta)
        max_vol = approx_max_volume_from_edge(h_layer_idx)
        x, y, z = seeds[layer_idx]
        mi.regions[layer_idx] = (
            float(x),
            float(y),
            float(z),
            float(shell_mat),
            float(max_vol),
        )

    # TetGen options: PLC (-p), quality (-q), region attrs (-A), volume (-a)
    switches = "pqAaY"  # -Y preserve PLC facets
    opts = Options(switches)
    opts.minratio = float(minratio)
    opts.regionattrib = True
    opts.verbose = bool(verbose)
    if max_steiner is not None:
        opts.parse_switches(f"S{int(max_steiner)}")
    if no_exact:
        opts.parse_switches("X")

    shell = build(
        mi,
        options=opts,
        attributes=True,
        volume_constraints=True,
        verbose=bool(verbose),
    )
    knt_shell = np.asarray(shell.points, dtype=np.float64)
    tets_shell = np.asarray(shell.elements, dtype=np.int64)

    # Region attributes may be absent; in either case, set material id to shell_mat
    mat_shell = np.full(tets_shell.shape[0], shell_mat, dtype=np.int32)
    ijk_shell = np.hstack([tets_shell.astype(np.int32), mat_shell.reshape(-1, 1)])

    # Merge body + shell: append then weld
    knt_all = np.vstack([knt0, knt_shell])
    ijk_shell_shifted = ijk_shell.copy()
    ijk_shell_shifted[:, :4] += knt0.shape[0]
    ijk_merged = np.vstack([ijk_body, ijk_shell_shifted])

    knt_weld, ijk_weld, n_fused = weld_points(knt_all, ijk_merged, tol=1e-12)
    if n_fused:
        log(f"[validate] welded duplicate nodes: {n_fused}")

    ijk_weld[:, :4] = orient_tets_positive(knt_weld, ijk_weld[:, :4])
    ijk_weld = remove_degenerate_and_duplicate_tets(knt_weld, ijk_weld)
    return knt_weld, ijk_weld


# ----------------------------------------------------------------------
# Public entry point (importable) – pure in-memory (no writes)
# ----------------------------------------------------------------------
def run_add_shell_pipeline(  # noqa: D417
    *,
    in_npz: str,
    # Geometry controls
    layers: int | None = None,
    K: float | None = 1.5,
    KL: float | None = 10.0,
    auto_layers: bool = False,
    auto_K: bool = False,
    # Mesh-size coupling
    beta: float = 1.0,
    same_scaling: bool = False,
    # Radial center
    center: str | tuple[float, float, float] = "0,0,0",
    # Size targets
    h0: float | None = None,
    hmax: float | None = None,
    body_h: float | None = None,
    # TetGen options
    minratio: float = 1.4,
    max_steiner: int | None = None,
    no_exact: bool = False,
    verbose: bool = False,
    shell_type: str = "box",
) -> tuple[np.ndarray, np.ndarray]:
    """Programmatic entry point for adding graded shell layers.

    Args:
        in_npz (str): Path to input NPZ mesh.
        layers (int | None): Number of layers.
        K (float | None): Geometric factor.
        KL (float | None): Outermost geometric scale.
        auto_layers (bool): Derive layers from KL and K.
        auto_K (bool): Derive K from KL and layers.
        beta (float): Size coupling factor.
        same_scaling (bool): Use linear size scaling.
        center (str | tuple[float, float, float]): Ray origin.
        h0 (float | None): Size near body.
        hmax (float | None): Size at boundary.
        body_h (float | None): Override for body surface size.
        minratio (float): TetGen quality constraint.
        max_steiner (int | None): Limit on Steiner points.
        no_exact (bool): Suppress exact arithmetic.
        verbose (bool): Verbose logging.

    Returns:
        tuple[np.ndarray, np.ndarray]: (fused nodes, fused connectivity).
    """
    # Load input
    data = np.load(in_npz)
    if "knt" not in data or "ijk" not in data:
        raise KeyError("Input NPZ must contain 'knt' and 'ijk'.")
    knt0 = data["knt"].astype(np.float64)
    ijk0 = data["ijk"].astype(np.int64)

    # Center parsing (supports str "cx,cy,cz" or tuple)
    if isinstance(center, str):
        cx, cy, cz = parse_csv3(center)
    else:
        cx, cy, cz = (float(center[0]), float(center[1]), float(center[2]))

    # Ensure we have a mat_id column for surface processing where needed
    if ijk0.shape[1] >= 5:
        ijk_body = ijk0[:, :5].astype(np.int32)
    else:
        ijk_body = np.hstack([ijk0[:, :4].astype(np.int32), np.ones((ijk0.shape[0], 1), dtype=np.int32)])  # dummy mat

    # ---- Determine geometry triplet (L, K, KL) based on flags ----
    if auto_layers and auto_K:
        raise ValueError("Choose only one: auto_layers or auto_K.")

    L = layers
    K_val = K
    KL_val = KL

    if (L is None) and (KL_val is not None) and (K_val is not None) and not auto_K:
        auto_layers = True

    if auto_layers:
        if (KL_val is None) or (K_val is None):
            raise ValueError("auto_layers requires both KL and K.")
        if KL_val <= 1.0 or K_val <= 1.0:
            raise ValueError("Require KL>1 and K>1 for auto_layers.")
        L = max(1, int(round(math.log(KL_val) / math.log(K_val))))
        if verbose:
            log(f"[geom] auto-layers: KL={KL_val:g}, K={K_val:g} -> layers L={L}")
    elif auto_K:
        if (KL_val is None) or (L is None):
            raise ValueError("auto_K requires both KL and layers.")
        if KL_val <= 1.0 or L < 1:
            raise ValueError("Require KL>1 and layers>=1.")
        K_val = KL_val ** (1.0 / L)
        if verbose:
            log(f"[geom] auto-K: KL={KL_val:g}, L={L} -> K={K_val:.8g}")
    else:
        # Neither auto; require at least L and K
        if (L is None) or (K_val is None):
            raise ValueError("Provide layers and K, or use auto_layers (KL & K) or auto_K (KL & layers).")
        if L < 1 or K_val <= 1.0:
            raise ValueError("Require layers>=1 and K>1.")

    # ---- Mesh-size defaults from body surface ----
    if body_h is None:
        body_h_val = estimate_body_h_from_surface(knt0, ijk_body)
        if verbose:
            log(f"[size] Derived body_h (median boundary-edge): {body_h_val:.6g}")
    else:
        body_h_val = float(body_h)
        if verbose:
            log(f"[size] Using user-provided body_h: {body_h_val:.6g}")

    if h0 is None:
        if hmax is not None:
            # Derive h0 by scaling down from hmax
            h0_val = float(hmax) / (K_val ** (L * (1.0 if same_scaling else beta)))
            if verbose:
                log(f"[size] h0 not given -> derived from hmax by scaling down: h0 = hmax / K^(L*beta) = {h0_val:.6g}")
        else:
            h0_val = 1.5 * body_h_val
            if verbose:
                log(f"[size] h0 not given -> set h0 = 1.5 * body_h = {h0_val:.6g}")
    else:
        h0_val = float(h0)
        if verbose:
            log(f"[size] Using user-provided h0: {h0_val:.6g}")

    # If hmax not provided and same_scaling is requested, set hmax = h0 * (K^L)
    if (hmax is None) and same_scaling:
        hmax_val = h0_val * (K_val ** (L))
        if verbose:
            log(f"[size] same-scaling: set hmax = h0 * K^L = {hmax_val:.6g}")
    else:
        hmax_val = float(hmax) if (hmax is not None) else None

    if verbose:
        log(
            f"[info] Geometry: L={L}, K={K_val:.6g}, "
            f"KL(req)={'-' if KL_val is None else f'{KL_val:.6g}'}, "
            f"KL(achieved)={(K_val**L):.6g}"
        )
    if verbose:
        log(
            f"[info] Mesh-size: beta={1.0 if same_scaling else beta}, "
            f"h0={h0_val:.6g}, "
            f"hmax={'(derived)' if hmax_val is None else f'{hmax_val:.6g}'}"
        )
        log(
            f"[info] center=({cx},{cy},{cz}), minratio={minratio}, "
            f"max_steiner={'-' if max_steiner is None else max_steiner}, "
            f"no_exact={bool(no_exact)}"
        )

    # ---- Build shells & mesh them ----
    knt, ijk = add_shell_with_meshpy(
        knt0,
        ijk0,
        layers=L,
        K=K_val,
        beta=(1.0 if same_scaling else beta),
        center=(cx, cy, cz),
        h0=h0_val,
        hmax=hmax_val,
        minratio=minratio,
        max_steiner=max_steiner,
        no_exact=bool(no_exact),
        verbose=bool(verbose),
        same_scaling=bool(same_scaling),
        shell_type=shell_type,
    )

    # Analyze and print airbox mesh quality
    if ijk.shape[1] >= 5:
        max_mat = int(ijk[:, 4].max())
        shell_mask = ijk[:, 4] == max_mat
        tets_shell = ijk[shell_mask, :4].astype(np.int64)
        tets_core = ijk[~shell_mask, :4].astype(np.int64)
    else:
        tets_shell = ijk[:, :4]
        tets_core = np.array([])

    n_shell = tets_shell.shape[0]
    n_core = tets_core.shape[0]

    if n_shell > 0:
        shell_nids = np.unique(tets_shell)
        shell_pts = knt[shell_nids]
        mins = np.min(shell_pts, axis=0)
        maxs = np.max(shell_pts, axis=0)
        extents = maxs - mins
        vol_airbox = float(np.prod(extents))
        q_shell = compute_tet_quality(knt, tets_shell)
        q_mean, q_min = float(np.mean(q_shell)), float(np.min(q_shell))
        ext_str = f"[{extents[0]:.1f}, {extents[1]:.1f}, {extents[2]:.1f}]"

        log("\n" + "=" * 70)
        log("=== AIRBOX MESH ANALYSIS ===")
        log(f"Core Elements  : {n_core:,}")
        log(f"Shell Elements : {n_shell:,} (Total: {ijk.shape[0]:,})")
        log(f"Nodes          : {knt.shape[0]:,}")
        log(f"Airbox Extents : {ext_str}")
        log(f"Airbox Volume  : {vol_airbox:.2e}")
        log(f"Shell Quality  : Mean = {q_mean:.4f}, Min = {q_min:.4f}")
        log("=" * 70 + "\n")
    else:
        log(f"[info] No shell elements added. Core nodes = {knt.shape[0]}, elements = {ijk.shape[0]}")

    return knt, ijk


# ------------------------------ CLI (optional) ----------------------------------


def main(argv: Sequence[str] | None = None) -> None:
    """CLI entry point for adding graded shell layers.

    Parses command line arguments and invokes run_add_shell_pipeline.

    Args:
        argv: Command arguments. Uses `sys.argv` when omitted.
    """
    ap = argparse.ArgumentParser(
        prog="tommos add-shell",
        description="Add graded exterior tetrahedral layers using MeshPy/TetGen (in-memory).",
    )
    ap.add_argument(
        "--in",
        dest="in_npz",
        required=True,
        help="Input NPZ mesh containing core body 'knt' and 'ijk'.",
    )
    ap.add_argument(
        "--layers",
        type=int,
        default=None,
        help="Number of graded tetrahedral shell layers L (>= 1).",
    )
    ap.add_argument(
        "--K",
        type=float,
        default=1.5,
        help="Geometric scale factor (> 1) for the outermost shell S_L = K^L * S_0.",
    )
    ap.add_argument(
        "--KL",
        type=float,
        default=10.0,
        help="Total outermost geometric scale relative to body (> 1).",
    )
    ap.add_argument(
        "--auto-layers",
        action="store_true",
        help="Automatically compute the number of layers L given --KL and --K.",
    )
    ap.add_argument(
        "--auto-K",
        action="store_true",
        help="Automatically compute the per-layer factor K given --KL and --layers.",
    )
    ap.add_argument(
        "--beta",
        type=float,
        default=1.0,
        help="Mesh-size/geometry coupling exponent (h_l = h0 * (scale**beta)^(l+1)).",
    )
    ap.add_argument(
        "--same-scaling",
        action="store_true",
        help="Shortcut: enforce beta=1.0 and sets target hmax = h0 * K**L.",
    )
    ap.add_argument(
        "--center",
        type=str,
        default="0,0,0",
        help="Ray origin for homothetic expansion as 'cx,cy,cz' (mesh units).",
    )
    ap.add_argument(
        "--h0",
        type=float,
        default=None,
        help="Target edge length for first shell layer. Defaults to 1.5 * body_h.",
    )
    ap.add_argument(
        "--hmax",
        type=float,
        default=None,
        help="Target edge length at the outermost shell boundary (mesh units).",
    )
    ap.add_argument(
        "--body-h",
        type=float,
        default=None,
        help="Body mesh size override. If omitted, derived from surface edge length.",
    )
    ap.add_argument(
        "--minratio",
        type=float,
        default=1.4,
        help="TetGen quality minratio (-q) for shell tetrahedra.",
    )
    ap.add_argument(
        "--max-steiner",
        type=int,
        default=None,
        help="Limit Steiner points added by TetGen (-S#).",
    )
    ap.add_argument("--no-exact", action="store_true", help="Suppress TetGen exact arithmetic (-X).")
    ap.add_argument("--verbose", action="store_true", help="Enable verbose TetGen output.")
    ap.add_argument(
        "--shell-type",
        type=str,
        default="hull",
        choices=["triangles", "hull"],
        help="Outer shell boundary type: copy original 'triangles' or use convex 'hull' (default).",
    )

    # NEW: optional VTU export of the merged (body + shells) mesh
    ap.add_argument(
        "--out-npz",
        type=str,
        default=None,
        help="Optional path to save the merged mesh as an NPZ file.",
    )
    ap.add_argument(
        "--out-vtu",
        type=str,
        default=None,
        help="Optional path to save the merged mesh as a VTU file for visualization.",
    )

    args = ap.parse_args(argv)

    knt, ijk = run_add_shell_pipeline(
        in_npz=args.in_npz,
        layers=args.layers,
        K=args.K,
        KL=args.KL,
        auto_layers=bool(args.auto_layers),
        auto_K=bool(args.auto_K),
        beta=float(args.beta),
        same_scaling=bool(args.same_scaling),
        center=args.center,  # string "cx,cy,cz" is accepted
        h0=args.h0,
        hmax=args.hmax,
        body_h=args.body_h,
        minratio=float(args.minratio),
        max_steiner=args.max_steiner,
        no_exact=bool(args.no_exact),
        verbose=bool(args.verbose),
        shell_type=args.shell_type,
    )
    print(f"[ok] merged in-memory mesh: nodes={knt.shape[0]:,}, tets={ijk.shape[0]:,}")

    # Optional VTU export
    if args.out_vtu:
        out_vtu = str(Path(args.out_vtu).with_suffix(".vtu"))
        cells = [("tetra", ijk[:, :4].astype(np.int32))]
        cell_data = {"mat_id": [ijk[:, 4].astype(np.int32)]}
        meshio.Mesh(points=knt.astype(np.float64), cells=cells, cell_data=cell_data).write(out_vtu)
        print(f"[ok] wrote VTU -> {out_vtu}")

    if args.out_npz:
        out_npz = str(Path(args.out_npz).with_suffix(".npz"))
        np.savez(out_npz, knt=knt.astype(np.float64), ijk=ijk.astype(np.int32))


if __name__ == "__main__":
    main()
