"""io_utils.py.

Simple output utilities including ASCII VTK UnstructuredGrid (.vtu) writer.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

import numpy as np


def ensure_dir(path: str | Path) -> Path:
    """Ensure that a directory exists, creating it if necessary.

    Args:
        path (str | Path): The path to the directory.

    Returns:
        Path: The Path object for the directory.
    """
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    return p


def write_hysteresis_header(csv_path: str | Path, extra_cols: Sequence[str] = ("E", "gnorm")) -> None:
    """Write the header for a hysteresis CSV file.

    Args:
        csv_path (str | Path): Path to the CSV file.
        extra_cols (Sequence[str], optional): Additional column names.
            Defaults to ("E", "gnorm").

    Example:
        >>> write_hysteresis_header("hysteresis.csv")
    """
    csv_path = Path(csv_path)
    cols = ["config", "B_ext_T", "J_par_T"] + list(extra_cols)
    csv_path.write_text(",".join(cols) + "\n", encoding="utf-8")


def append_hysteresis_row(
    csv_path: str | Path,
    config_idx: int,
    H: float,
    M_parallel: float,
    E: float | None = None,
    gnorm: float | None = None,
) -> None:
    """Append a single data row to a hysteresis CSV file.

    Args:
        csv_path (str | Path): Path to the CSV file.
        config_idx (int): Current configuration index.
        H (float): Applied external field (Tesla).
        M_parallel (float): Parallel component of magnetic polarization (Tesla).
        E (float, optional): Total energy. Defaults to None.
        gnorm (float, optional): Norm of the energy gradient. Defaults to None.

    Example:
        >>> append_hysteresis_row("hysteresis.csv", 0, 1.0, 0.8, E=-123.4, gnorm=1e-5)
    """
    csv_path = Path(csv_path)
    parts = [str(config_idx), f"{H:.9e}", f"{M_parallel:.9e}"]
    if E is not None:
        parts.append(f"{E:.9e}")
    if gnorm is not None:
        parts.append(f"{gnorm:.9e}")
    with csv_path.open("a", encoding="utf-8") as f:
        f.write(",".join(parts) + "\n")


def write_mh(path: str | Path, records: np.ndarray) -> None:
    """Write a mammos-mumag compatible .mh (magnetization history) file.

    The file contains columns: B_ext [T], J_parallel [T], mx, my, mz, E [J/m^3].

    Args:
        path (str | Path): Base path for the output file (extension .mh added).
        records (np.ndarray): Data records of shape (N, 6).

    Example:
        >>> data = np.zeros((10, 6))
        >>> write_mh("results", data)
    """
    path = Path(path).with_suffix(".mh")
    header = "B_ext [T]  J_parallel [T]  mx  my  mz  E [J/m^3]"
    with open(path, "w") as f:
        f.write("# " + header + " \n")
        np.savetxt(f, records, fmt="%.9e")


def compute_volume_averaged_J_parallel(
    m_nodes: np.ndarray,
    conn: np.ndarray,
    volume: np.ndarray,
    mat_id: np.ndarray,
    Js_lookup: np.ndarray,
    h_dir: np.ndarray,
) -> float:
    """Compute the volume-averaged magnetic polarization parallel to a direction.

    Args:
        m_nodes (np.ndarray): Nodal unit magnetization vectors (N, 3).
        conn (np.ndarray): Tetrahedron connectivity (E, 4).
        volume (np.ndarray): Element volumes (E,).
        mat_id (np.ndarray): Element material IDs (E,).
        Js_lookup (np.ndarray): Saturation polarization lookup table.
        h_dir (np.ndarray): Target direction vector (3,).

    Returns:
        float: Volume-averaged J_parallel in the same units as Js_lookup.
    """
    h = np.asarray(h_dir, dtype=np.float64)
    h /= np.linalg.norm(h) + 1e-30

    m_nodes = np.asarray(m_nodes, dtype=np.float64)
    conn = np.asarray(conn, dtype=np.int64)
    volume = np.asarray(volume, dtype=np.float64)
    mat_id = np.asarray(mat_id, dtype=np.int64)
    Js_lookup = np.asarray(Js_lookup, dtype=np.float64)

    m_e = m_nodes[conn]
    m_avg = m_e.mean(axis=1)
    Js_e = Js_lookup[mat_id - 1]
    J_e = Js_e[:, None] * m_avg

    # Normalize by magnetic volume
    Vmag = volume[Js_e > 0].sum() + 1e-30
    J_avg = (volume[:, None] * J_e).sum(axis=0) / Vmag
    return float(J_avg.dot(h))


def _vtk_type(arr: np.ndarray) -> str:
    """Return the VTK XML data type string for a given numpy array.

    Args:
        arr (np.ndarray): The input numpy array.

    Returns:
        str: VTK type string (e.g., "Float32", "Int32").
    """
    if arr.dtype == np.float32:
        return "Float32"
    if arr.dtype == np.float64:
        return "Float64"
    if arr.dtype == np.int32:
        return "Int32"
    if arr.dtype == np.int64:
        return "Int64"
    if arr.dtype == np.uint8:
        return "UInt8"
    if np.issubdtype(arr.dtype, np.integer):
        return "Int32"
    return "Float32"


def write_vtu_tetra(
    path: str | Path,
    points: np.ndarray,
    tets: np.ndarray,
    *,
    point_data: dict[str, np.ndarray] | None = None,
    cell_data: dict[str, np.ndarray] | None = None,
) -> None:
    """Write a tetrahedral mesh to an ASCII VTK UnstructuredGrid (.vtu) file.

    Args:
        path (str | Path): Output file path.
        points (np.ndarray): Node coordinates (N, 3).
        tets (np.ndarray): Tetrahedron connectivity (E, 4).
        point_data (dict[str, np.ndarray] | None, optional): Dictionary of
            nodal data arrays (N, ...). Defaults to None.
        cell_data (dict[str, np.ndarray] | None, optional): Dictionary of
            element-wise data arrays (E, ...). Defaults to None.

    Raises:
        ValueError: If array shapes do not match the number of points or cells.

    Example:
        >>> points = np.array([[0,0,0], [1,0,0], [0,1,0], [0,0,1]])
        >>> tets = np.array([[0, 1, 2, 3]])
        >>> write_vtu_tetra("mesh.vtu", points, tets, point_data={"pot": [0,1,2,3]})
    """
    path = Path(path)
    point_data = point_data or {}
    cell_data = cell_data or {}

    pts = np.asarray(points)
    if pts.ndim != 2 or pts.shape[1] != 3:
        raise ValueError("points must have shape (N,3)")
    cells = np.asarray(tets)
    if cells.ndim != 2 or cells.shape[1] != 4:
        raise ValueError("tets must have shape (E,4)")

    N = pts.shape[0]
    E = cells.shape[0]

    pts = pts.astype(np.float32, copy=False)
    conn = cells.astype(np.int32, copy=False).reshape(-1)
    offsets = np.arange(1, E + 1, dtype=np.int32) * 4
    types = np.full((E,), 10, dtype=np.uint8)

    def fmt(a: np.ndarray) -> str:
        return " ".join(map(str, a.reshape(-1).tolist()))

    lines = []
    lines.append('<?xml version="1.0"?>')
    lines.append('<VTKFile type="UnstructuredGrid" version="0.1" byte_order="LittleEndian">')
    lines.append("  <UnstructuredGrid>")
    lines.append(f'    <Piece NumberOfPoints="{N}" NumberOfCells="{E}">')

    lines.append("      <Points>")
    lines.append(f'        <DataArray type="{_vtk_type(pts)}" NumberOfComponents="3" format="ascii">')
    lines.append("          " + fmt(pts))
    lines.append("        </DataArray>")
    lines.append("      </Points>")

    lines.append("      <Cells>")
    lines.append('        <DataArray type="Int32" Name="connectivity" format="ascii">')
    lines.append("          " + fmt(conn))
    lines.append("        </DataArray>")
    lines.append('        <DataArray type="Int32" Name="offsets" format="ascii">')
    lines.append("          " + fmt(offsets))
    lines.append("        </DataArray>")
    lines.append('        <DataArray type="UInt8" Name="types" format="ascii">')
    lines.append("          " + fmt(types))
    lines.append("        </DataArray>")
    lines.append("      </Cells>")

    lines.append("      <PointData>")
    for name, arr in point_data.items():
        a = np.asarray(arr)
        if a.shape[0] != N:
            raise ValueError(f"PointData '{name}' length mismatch")
        ncomp = 1 if a.ndim == 1 else a.shape[1]
        a_out = a.astype(np.int32 if np.issubdtype(a.dtype, np.integer) else np.float32, copy=False)
        lines.append(
            f'        <DataArray type="{_vtk_type(a_out)}" Name="{name}" NumberOfComponents="{ncomp}" format="ascii">'
        )
        lines.append("          " + fmt(a_out))
        lines.append("        </DataArray>")
    lines.append("      </PointData>")

    lines.append("      <CellData>")
    for name, arr in cell_data.items():
        a = np.asarray(arr)
        if a.shape[0] != E:
            raise ValueError(f"CellData '{name}' length mismatch")
        ncomp = 1 if a.ndim == 1 else a.shape[1]
        a_out = a.astype(np.int32 if np.issubdtype(a.dtype, np.integer) else np.float32, copy=False)
        lines.append(
            f'        <DataArray type="{_vtk_type(a_out)}" Name="{name}" NumberOfComponents="{ncomp}" format="ascii">'
        )
        lines.append("          " + fmt(a_out))
        lines.append("        </DataArray>")
    lines.append("      </CellData>")

    lines.append("    </Piece>")
    lines.append("  </UnstructuredGrid>")
    lines.append("</VTKFile>")

    path.write_text("\n".join(lines), encoding="utf-8")


def convert_sim_csv_to_mammos(csv_path: str | Path, out_path: str | Path | None = None, Js_ref: float = 1.0) -> None:
    """Convert the raw hysteresis.csv into a mammos_entity.EntityCollection CSV.

    Args:
        csv_path (str | Path): Path to the input raw CSV.
        out_path (str | Path | None): Path to the output CSV. If None, overwrites csv_path.
        Js_ref (float): Reference saturation polarization in Tesla. Used to rescale energy density.
    """
    csv_path = Path(csv_path)
    if not csv_path.exists():
        return

    out_path = Path(out_path) if out_path else csv_path

    import mammos_entity as me

    try:
        # The first row is the header: config, B_ext_T, J_par_T, E, gnorm
        data = np.loadtxt(csv_path, delimiter=",", skiprows=1)
        if data.ndim == 1:
            data = data[None, :]
        if data.size == 0:
            return

        config_col = data[:, 0].tolist()
        B_ext_col = data[:, 1]
        J_par_col = data[:, 2]

        c = me.EntityCollection(
            config=me.Entity("Index", config_col),
            B_ext_T=me.Entity("MagneticFluxDensity", B_ext_col, "T"),
            J_par_T=me.Entity("MagneticPolarisation", J_par_col, "T"),
        )

        # Kd_ref to scale dimensionless energy density to J/m^3
        MU0_SI = 4e-7 * np.pi
        Kd_ref = (Js_ref**2) / (2.0 * MU0_SI)

        # Add E and gnorm if they exist
        if data.shape[1] > 3:
            E_col = data[:, 3] * Kd_ref
            c.E = me.Entity("EnergyDensity", E_col, "J/m^3")
        if data.shape[1] > 4:
            gnorm_col = data[:, 4] * Kd_ref
            c.gnorm = me.Entity("EnergyDensity", gnorm_col, "J/m^3")

        c.to_csv(out_path)
    except Exception as e:
        print(f"[warning] Failed to convert CSV to mammos_entity format: {e}")
